Ini, TOML
[build]
  command = "quasar build"
  publish = "dist/spa"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
